<a href="https://colab.research.google.com/github/jermania321/brocode2.0/blob/master/Numpy_Matrix_and_Matrix_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrices and Matrix Arithmetic



*   Matrices are a foundational element of linear algebra
*   Matrices are used throughout in the field of machine learning for the description of algorithms and processes


*   A matrix is a two-dimensional array of scalars with one or more columns and one or more rows.






# Defining a Matrix

We can represent a matrix in Python using a two-dimensional NumPy array. A 2D NumPy array can be constructed using a list of lists.

For example, below is a 2 row, 3 column matrix.

In [ ]:
# create matrix
from numpy import array
A = array([[1, 2, 3], [4, 5, 6]])
print(A)

[[1 2 3]
 [4 5 6]]


# Matrix Arithmetic

**Matrix Addition**

In [ ]:
# matrix addition
from numpy import array
# define first matrix
A = array([[1, 2, 3],[4, 5, 6]])
print('matrix A')
print(A)
# define second matrix
B = array([[1, 2, 3],[4, 5, 6]])
print('matrix B')
print(B)
# add matrices
C = A + B
print('sum of A and B')
print(C)

matrix A
[[1 2 3]
 [4 5 6]]
matrix B
[[1 2 3]
 [4 5 6]]
sum of A and B
[[ 2  4  6]
 [ 8 10 12]]


**Matrix Subtraction**

In [ ]:
# matrix subtraction
from numpy import array
# define first matrix
A = array([[1, 2, 3],[4, 5, 6]])
print('Matrix A')
print(A)
# define second matrix
B = array([[0.5, 0.5, 0.5],[0.5, 0.5, 0.5]])
print('Matrix B')
print(B)
# subtract matrices
C = A - B
print('Matrix C')
print(C)

Matrix A
[[1 2 3]
 [4 5 6]]
Matrix B
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]]
Matrix C
[[0.5 1.5 2.5]
 [3.5 4.5 5.5]]


**Matrix Multiplication (Hadamard Product)**

Two matrices with the same size can be multiplied together, and this is often called element-wise matrix multiplication or the Hadamard product. It is not the typical operation meant when referring to matrix multiplication.

In [ ]:
# matrix Hadamard product
from numpy import array
# define first matrix
A = array([[1, 2, 3],[4, 5, 6]])
print('matrix A')
print(A)
# define second matrix
B = array([[1, 2, 3],[4, 5, 6]])
print('matrix B')
print(B)
# multiply matrices
C = A * B
print('matrix C')
print(C)

matrix A
[[1 2 3]
 [4 5 6]]
matrix B
[[1 2 3]
 [4 5 6]]
matrix C
[[ 1  4  9]
 [16 25 36]]


**Matrix Division**

In [ ]:
# matrix division
from numpy import array
# define first matrix
A = array([[1, 2, 3],[4, 5, 6]])
print(A)
# define second matrix
B = array([[1, 2, 3],[4, 5, 6]])
print(B)
# divide matrices
C = A / B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1. 1. 1.]
 [1. 1. 1.]]


**Matrix-Matrix Multiplication**
Matrix multiplication, also called the matrix dot product is more complicated than the previous
operations and involves a rule as not all matrices can be multiplied together.

C = A.B

or

C = AB

The rule for matrix multiplication is as follows:

The number of columns (n) in the first matrix (A) must equal the number of rows (m) in
the second matrix (B).

For example, matrix A has the dimensions m rows and n columns and matrix B has the dimensions n and k. The n columns in A and n rows in B are equal. The result is a new matrix with m rows and k columns.

C(m; k) = A(m; n) . B(n; k)

In [ ]:
# matrix dot product
from numpy import array
print('first matrix')
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
print('second matrix')
B = array([
[1, 2],
[3, 4]])
print(B)
print('product')
C = A.dot(B)
print(C)
print('multiply matrices with @ operator')
D = A @ B
print(D)

first matrix
[[1 2]
 [3 4]
 [5 6]]
second matrix
[[1 2]
 [3 4]]
product
[[ 7 10]
 [15 22]
 [23 34]]
multiply matrices with @ operator
[[ 7 10]
 [15 22]
 [23 34]]


**Matrix-Vector Multiplication**

A matrix and a vector can be multiplied together as long as the rule of matrix multiplication is observed. Speci cally, that the number of columns in the matrix must equal the number of items in the vector. As with matrix multiplication, the operation can be written using the dot notation. Because the vector only has one column, the result is always a vector.

c = A . v

In [ ]:
# matrix-vector multiplication
from numpy import array
print('matrix') 
A = array([[1, 2],[3, 4],[5, 6]])
print(A)
# define vector
print('vector') 
B = array([0.5, 0.5])
print(B)
# multiply
C = A.dot(B)
print('Result')
print(C)

matrix
[[1 2]
 [3 4]
 [5 6]]
vector
[0.5 0.5]
Result
[1.5 3.5 5.5]


**Matrix-Scalar Multiplication**

A matrix can be multiplied by a scalar. This can be represented using the dot notation between
the matrix and the scalar.

C = A. b

In [ ]:
# matrix-scalar multiplication
from numpy import array
# define matrix
print('matrix')
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
# define scalar
print("scalar")
b = 0.5
print(b)
# multiply
C = A * b
print('result')
print(C)

matrix
[[1 2]
 [3 4]
 [5 6]]
scalar
0.5
result
[[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]


# Types of Matrices

A lot of linear algebra is concerned with operations on vectors and matrices, and there are many different types of matrices

The following are few types of matrices that used particullarly in the parts of linear algebra relevant to machine learning.

**Square Matrix**

A square matrix is a matrix where the number of rows (n) is equivalent to the number of columns (m).

**Symmetric Matrix**

A symmetric matrix is a type of square matrix where the top-right triangle is the same as the bottom-left triangle.It is no exaggeration to say that symmetric matrices S are the most important matrices the world will ever see  in the theory of linear algebra and also in the applications.

**Triangular Matrix**

A triangular matrix is a type of square matrix that has all values in the upper-right or lower-left of the matrix with the remaining elements lled with zero values. A triangular matrix with values only above the main diagonal is called an upper triangular matrix. Whereas, a triangular matrix with values only below the main diagonal is called a lower triangular matrix.

In [ ]:
# triangular matrices
from numpy import array
from numpy import tril
from numpy import triu
# define square matrix
M = array([[1, 2, 3],[1, 2, 3],[1, 2, 3]])
print(M)
print('lower triangular matrix')
lower = tril(M)
print(lower)
print('upper triangular matrix')
upper = triu(M)
print(upper)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
lower triangular matrix
[[1 0 0]
 [1 2 0]
 [1 2 3]]
upper triangular matrix
[[1 2 3]
 [0 2 3]
 [0 0 3]]


**Diagonal Matrix**
A diagonal matrix is one where values outside of the main diagonal have a zero value, where the
main diagonal is taken from the top left of the matrix to the bottom right. A diagonal matrix
is often denoted with the variable D and may be represented as a full matrix or as a vector of
values on the main diagonal.

Diagonal matrices consist mostly of zeros and have non-zero entries only along the main diagonal.

In [ ]:
# diagonal matrix
from numpy import array
from numpy import diag
# define square matrix
print('matrix')
M = array([[1, 2, 3],[1, 2, 3],[1, 2, 3]])
print(M)
#extract diagonal vector
d = diag(M)
print('diagonal vector')
print(d)
# create diagonal matrix from vector
D = diag(d)
print('diagonal matrix')
print(D)

matrix
[[1 2 3]
 [1 2 3]
 [1 2 3]]
diagonal vector
[1 2 3]
diagonal matrix
[[1 0 0]
 [0 2 0]
 [0 0 3]]


**Identity Matrix**

An identity matrix is a square matrix that does not change a vector when multiplied. The values of an identity matrix are known. All of the scalar values along the main diagonal (top-left to bottom-right) have the value one, while all other values are zero.

In [ ]:
# identity matrix
from numpy import identity
I = identity(3)
#I=eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Orthogonal Matrix**

Two vectors are orthogonal when their dot product equals zero. The length of each vector is 1 then the vectors are called orthonormal because they are both orthogonal and normalized.

In [ ]:
# orthogonal matrix
from numpy import array
from numpy.linalg import inv
# define orthogonal matrix
Q = array([[1, 0],[0, -1]])
print(Q)
# inverse equivalence
V = inv(Q)
print(Q.T)
print(V)
# identity equivalence
I = Q.dot(Q.T)
print(I)

[[ 1  0]
 [ 0 -1]]
[[ 1  0]
 [ 0 -1]]
[[ 1.  0.]
 [-0. -1.]]
[[1 0]
 [0 1]]


# Matrix Operations